# Site settings
title: "Imran's Portfolio"
email: "i.anwar2004@gmail.com"
description: "Helping businesses with automation, financial modeling, and analytics."
baseurl: "" # Leave empty for GitHub Pages
url: "https://imrananwar.github.io" # Your GitHub Pages URL

# Social Links
github_username: "mimrananwar"
linkedin_username: "mimrananwar"


# Build settings
markdown: markdown
